### PR TITLE
Add conda-forge badge

### PR DESCRIPTION
**Pull request by matthiasdiener**
Followup of #32.

**Describe your changes**
Add a badge to the README file pointing to the conda-forge memray package (and showing the package version available on conda-forge).

**Testing performed**
n/a

**Additional context**
We could add more text to the installation instructions in the README if it is of interest.

---

Here is how it looks like:

image

### CODE REVIEW

**Comment by pablogsal** [comment]
Looks great!! Any reason you marked the PR as draft?

**Comment by matthiasdiener** [comment]
> Looks great!! Any reason you marked the PR as draft?

No particular reason, I just wanted to wait in case you guys wanted to add more text.

**Comment by matthiasdiener** [comment]
> Looks great!! Any reason you marked the PR as draft?

No particular reason, I just wanted to wait in case you guys wanted to add more text.

**Review by pablogsal — APPROVED** [review]

**Comment by pablogsal** [comment]
No, this looks great!

**Pull request merged**
