### PR TITLE
Build musl x86-64 wheels

### PR DESCRIPTION
**Pull request by salticus**
#352 Set up CI to build and test musl libc wheels

**Describe your changes**
Enable musl builds in the pyproject file. Dependencies for memray are supplied using comparable libraries from the Alpine main repository.

**Testing performed**
Running against GitHub actions is producing long build times. Further changes may be necessary.

### CODE REVIEW

**Comment by pablogsal** [comment]
Hummmm, seems that `lldb` is missing from the alpine repo?

**Comment by pablogsal** [comment]
I have updated the PR skipping 32 bit muslinux wheels

**Comment by godlygeek** [comment]
> Hummmm, seems that `lldb` is missing from the alpine 32 bits repo?

We could make that install optional. We already do that for the manylinux builds. The test suite just skips that `memray attach` test when `lldb` isn't available.

> We probably don't want 32 bits muslc wheels in any case

But that's fine, too.

There were still a few failing tests even for musl x86-64. Looks like the old musl libc version in the musllinux_1_1 container implements `aligned_alloc` and `realloc` in terms of the `malloc` symbol in the PLT, so we needed to set the recursion guard in a few more places in the hooks to prevent double counting of allocations with those allocators.

**Review by godlygeek — APPROVED** [review]
Thanks a lot for the contribution, @salticus!

**Pull request merged**
