### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by kianmeng**

### CODE REVIEW

**Comment by godlygeek** [comment]
Thanks! Per our [contribution licensing](https://github.com/bloomberg/memray/blob/main/README.md#contribution-licensing) documentation, would you mind adding a `Signed-Off-By:` tag to your commit message to indicate that you have read and agree to our [Developer's Certificate of Origin](https://github.com/bloomberg/.github/blob/main/DCO.md)?

That should be as easy as doing:
```shell
$ git commit --amend -C HEAD -s
$ git push -f
```
from a checkout of this branch.

**Comment by kianmeng** [comment]
> Thanks! Per our [contribution licensing](https://github.com/bloomberg/memray/blob/main/README.md#contribution-licensing) documentation, would you mind adding a `Signed-Off-By:` tag to your commit message to indicate that you have read and agree to our [Developer's Certificate of Origin](https://github.com/bloomberg/.github/blob/main/DCO.md)?

@godlygeek Done.

**Review by godlygeek — APPROVED** [review]
LGTM - Thanks for the contribution! 🎉

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
