### PR TITLE
pre-commit autoupdate

### PR DESCRIPTION
**Pull request by cclauss**
*Issue number of the reported bug or feature request: #<number>*
* #500

**Describe your changes**
A clear and concise description of the changes you have made.
% `pre-commit autoupdate`

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.
% `pre-commit run --all-files`

**Additional context**
Add any other context about your contribution here.

### CODE REVIEW

**Comment by godlygeek** [comment]
Whoops, both of us made a change at the same time there.

@cclauss Why the downgrade of `mirrors-prettier` to `v2.7.1` ?

**Comment by cclauss** [comment]
> Why the downgrade of mirrors-prettier to v2.7.1 ?

https://github.com/bloomberg/memray/actions/runs/6984049688/job/19006277652
which made no sense to me because Node.js v16 was indeed installed.

**Comment by godlygeek** [comment]
Ah, "prettier requires at least version 14 of Node, please upgrade". Hm. But we're installing Node 16... 
```
Run actions/setup-node@v4
  with:
    node-version: 16
    always-auth: false
    check-latest: false
    token: ***
Found in cache @ /opt/hostedtoolcache/node/16.[2](https://github.com/bloomberg/memray/actions/runs/6984188977/job/19006591456?pr=501#step:3:2)0.2/x6[4](https://github.com/bloomberg/memray/actions/runs/6984188977/job/19006591456?pr=501#step:3:4)
Environment details
  node: v1[6](https://github.com/bloomberg/memray/actions/runs/6984188977/job/19006591456?pr=501#step:3:6).20.2
  npm: [8](https://github.com/bloomberg/memray/actions/runs/6984188977/job/19006591456?pr=501#step:3:9).1[9](https://github.com/bloomberg/memray/actions/runs/6984188977/job/19006591456?pr=501#step:3:10).4
  yarn: 1.22.21
```
Hm. I guess pre-commit isn't picking up the version that we installed...

**Comment by cclauss** [comment]
I tend to use pre-commit.ci instead of GHA to run pre-commit.

**Comment by godlygeek** [comment]
I think I've got it. `nodeenv` prefers a binary named `nodejs` over one named `node`:

https://github.com/ekalinin/nodeenv/blob/eaa9de97e561ab4f99458c94633e92547e72d5f1/nodeenv.py#L931-L938

And `actions/setup-node` isn't installing a `nodejs`, but there is one in /usr/bin on the runner, so that's getting chosen over the `node` we've just installed.

It seems we can hack around it by symlinking the `node` we install to `nodejs`, which, yuck, but oh well it seems to work...

**Comment by godlygeek** [comment]
I've entered https://github.com/actions/setup-node/issues/905 for that since that doesn't seem like expected behavior (though I'm not a JS person so it's entirely possible this is a nodeenv problem and not an actions/setup-node problem... we'll see)

**Review by godlygeek — APPROVED** [review]
Well, my terrible hack works well enough, so LGTM. Thanks @cclauss!

**Pull request merged**
