### PR TITLE
Improve the images of terminal output

### PR DESCRIPTION
**Pull request by pablogsal**
The images showing terminal reporters are a bit inconsistent because
every one of them is showing a different color scheme and they are not
very aesthetically pleasing. To improve this leverage
https://carbon.now.sh/ to show nice terminal images with the output in
the same color scheme (Dracula Pro).

Signed-off-by: Pablo Galindo <pablogsal@gmail.com>

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

### CODE REVIEW

**Comment by godlygeek** [comment]
For the stats reporter one, would you mind trimming off some of the extra blank space on the right side? That should make it look better on mobile - currently it's getting resized small enough that the text isn't readable without zooming in, which is annoying given how much of it is blank space.

There's also a few terminal screenshots in the live mode docs (live different thread, live disconnected, live running) - do you want to update those to be consistent?

**Comment by pablogsal** [comment]
> There's also a few terminal screenshots in the live mode docs (live different thread, live disconnected, live running) - do you want to update those to be consistent?

Those I will update later this PR. They integrate a bit better and don't bother me too much and they need some editing after pasting the text in carbon.sh

**Comment by pablogsal** [comment]
> For the stats reporter one, would you mind trimming off some of the extra blank space on the right side? That should make it look better on mobile - currently it's getting resized small enough that the text isn't readable without zooming in, which is annoying given how much of it is blank space.

Done

**Review by godlygeek — APPROVED** [review]
LGTM

**Pull request merged**
