### PR TITLE
Updates pip command to use python executable

### PR DESCRIPTION
**Pull request by kushaldas**
**Describe your changes**
Updates the `pip` command to use the `python3 -m pip` style.

**Testing performed**

None, update to README only.

**Additional context**

Following the good practice of using `pip`.

### CODE REVIEW

**Review by pablogsal — DISMISSED** [review]

**Comment by pablogsal** [comment]
Thanks a lot @kushaldas ❤️

**Comment by kushaldas** [comment]
@pablogsal Uh, I missed a few more, adding one more commit.

**Comment by kushaldas** [comment]
@pablogsal Forced pushed as this should not be two different commits, needs one more round of approval.

**Comment by kushaldas** [comment]
I guess it still needs the `approval` once again :)

**Review by pablogsal — APPROVED** [review]

**Pull request merged**
